version: "2"

tasks:
  build:
    cmds:
      - task setup
      - task build:linux
      - task build:windows

  setup:
    cmds:
      - rm -rf builds/
      - mkdir -p builds/linux
      - mkdir -p builds/windows

  build:linux:
    cmds:
      - docker build --no-cache -f Dockerfile -t oscar-broman/sky:linux .
      - docker run --volume=$(pwd)/builds:/work/builds oscar-broman/sky:linux

  build:windows:
    dir: builds/windows
    cmds:
      - cmake -G "Visual Studio 15 2017" ../..
      - cmake --build . --config Release
      - cpack
      - mv release-windows.zip ../
